M48
; DRILL file {KiCad 7.0.10} date Sun Feb 18 18:29:21 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-18T18:29:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X39.223Y-181.249
X40.137Y-36.52
X154.65Y-181.427
X154.681Y-35.992
M30
